### ISSUE TITLE
Update to v5.0.0

### ISSUE THREAD

**Issue by devurandom** [flathub/org.zulip.Zulip#13]
Version 5.0.0 was released recently with security fixes: https://github.com/zulip/zulip-desktop/blob/master/changelog.md#v500---2020-03-30

**Comment by ghisvail** [comment]
Feel free to submit a PR for it (have a look at https://github.com/flathub/org.zulip.Zulip/pull/11).

**Comment by lazka** [comment]
I'll look into the 5.0 update

**Comment by lazka** [comment]
See #14
