### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by devurandom** [flathub/org.zulip.Zulip#18]
Since updating to Zulip 5.0.0 (#13, #14), after startup no window appears and no tray icon is shown.  #10 and #17 did not fix this. It does not matter whether I start Zulip from KRunner / KDE Plasma or from the command line. With Zulip 4.0.3 this still worked: After startup a tray icon was shown.

```
❯ flatpak info org.zulip.Zulip

Zulip - Zulip Desktop Client for Linux

          ID: org.zulip.Zulip
         Ref: app/org.zulip.Zulip/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 5.0.0
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 454.3 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: 8421fcb1a6d0f91abff9ff7bca4cd695ccd1ef6c2da7a2f0dbd2c041dda7e386
      Parent: 3d6f107f27ed5227505dbca7018187fd6e6b1bbb9c819b39562d76371f165ca7
     Subject: Add missing desktop entry (88c9fa89)
        Date: 2020-04-05 17:35:05 +0000

❯ flatpak run org.zulip.Zulip
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(electron) 'setUserAgent function' is deprecated and will be removed. Please use 'userAgent property' instead.
(electron) 'setAudioMuted function' is deprecated and will be removed. Please use 'audioMuted property' instead.
^C⏎
[2:0406/085626.426640:FATAL:bus.cc(1220)] D-Bus connection was disconnected. Aborting.
Failed to generate minidump.~ took 13s 
```

**Comment by ghisvail** [comment]
Do you mean `flatpak run org.zulip.Zulip` does not start the application?

I get the following on my systems (Debian Bullseye and Pop!_OS 19.10):

```
$ flatpak info org.zulip.Zulip 

Zulip - Zulip Desktop Client for Linux

          ID: org.zulip.Zulip
         Ref: app/org.zulip.Zulip/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 5.0.0
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 454,3 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: 8421fcb1a6d0f91abff9ff7bca4cd695ccd1ef6c2da7a2f0dbd2c041dda7e386
      Parent: 3d6f107f27ed5227505dbca7018187fd6e6b1bbb9c819b39562d76371f165ca7
     Subject: Add missing desktop entry (88c9fa89)
        Date: 2020-04-05 17:35:05 +0000
```

```
$ flatpak run org.zulip.Zulip 
Gtk-Message: 12:41:29.287: Failed to load module "appmenu-gtk-module"
Gtk-Message: 12:41:29.355: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:41:29.355: Failed to load module "canberra-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
```

![Capture d’écran de 2020-04-06 12-44-08](https://user-images.githubusercontent.com/1964655/78550447-651fb300-7804-11ea-8c8b-2b28a12ec4c4.png)

**Comment by ghisvail** [comment]
Sadly, I am using GNOME exclusively, so interactions with the tray icon aren't something I can test and fix myself.

**Comment by devurandom** [comment]
> Do you mean `flatpak run org.zulip.Zulip` does not start the application?

It does start and it keeps running, but it does not show an application window or a tray icon.

I ran `jq '.startMinimized=true' .var/app/org.zulip.Zulip/config/Zulip/config/settings.json` and saved the ouput in the same file. Now the Zulip window comes up after starting the app. The tray icon is still missing, though.

**Comment by ghisvail** [comment]
> It does start and it keeps running, but it does not show an application window or a tray icon.

So you're not seeing the window shown on the screenshot above? Even after ensuring no leftover process is running in the background?

**Comment by fdcds** [comment]
I see the same behaviour on:
```
Operating System: Fedora 31
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.67.0
Qt Version: 5.13.2
Kernel Version: 5.5.13-200.fc31.x86_64
OS Type: 64-bit
```

**Comment by devurandom** [comment]
> > It does start and it keeps running, but it does not show an application window or a tray icon.
> 
> So you're not seeing the window shown on the screenshot above? Even after ensuring no leftover process is running in the background?

`flatpak ps` shows no org.zulip.Zulip processes and neither does `ps aux | rg zulip`.

No, I do not see the video from the screenshot after starting Zulip. This can be explained by `startMinimized=true` in my settings. With Zulip starting minimized to the tray and no tray icon being shown, that explains why I saw "nothing".

I later changed `startMinimized` to `false` (https://github.com/flathub/org.zulip.Zulip/issues/18#issuecomment-609762018; I originally swapped `true` and `false` when writing my comment; sorry for any confusion this might have caused) and then the window appeared after starting Zulip. But the tray icon was still missing.

```
Operating System: Gentoo Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.1
Kernel Version: 5.5.14
OS Type: 64-bit
```

**Comment by ghisvail** [comment]
> sorry for any confusion this might have caused

Then, you won't mind if I retitle this issue to remove said confusion.

> the tray icon was still missing

Looking at other Electron-based chat clients (RocketChat, Riot, Discord), it seems that support for tray icons is a headache.

Could you try running the flatpak with `--env=XDG_CURRENT_DESKTOP=Unity`?

**Comment by devurandom** [comment]
> > sorry for any confusion this might have caused
> 
> Then, you won't mind if I retitle this issue to remove said confusion.

At the time I wrote the title, I did not yet know whether Zulip's behaviour might have changed to no longer support minimisation to tray.

> > the tray icon was still missing
> 
> Looking at other Electron-based chat clients (RocketChat, Riot, Discord), it seems that support for tray icons is a headache.
> 
> Could you try running the flatpak with `--env=XDG_CURRENT_DESKTOP=Unity`?

Same behaviour: Window only appears when `startMinimized=false` and the tray icon never appears.

**Comment by ghisvail** [comment]
The move from v4.0.3 to v5.0.0 also upgraded Electron to v8.x which is bringing pain to everyone concerning tray icons. See the following [issue](https://github.com/zulip/zulip-desktop/issues/910) or this [one](https://github.com/electron/electron/issues/21445) for instance. Upstream should probably get involved with this.

**Comment by devurandom** [comment]
> The move from v4.0.3 to v5.0.0 also upgraded Electron to v8.x which is bringing pain to everyone concerning tray icons. See the following [issue](https://github.com/zulip/zulip-desktop/issues/910) or this [one](https://github.com/electron/electron/issues/21445) for instance. Upstream should probably get involved with this.

Thanks for digging this up!

See-Also: https://bugs.chromium.org/p/chromium/issues/detail?id=419673

**Comment by devurandom** [comment]
Upstream claims this is fixed with version 5.3.0: https://github.com/zulip/zulip-desktop/issues/936#issuecomment-649491698

**Comment by lazka** [comment]
Seems to work here. Can anyone confirm?

**Comment by devurandom** [comment]
> Seems to work here. Can anyone confirm?

I am at 5.4.2 and the issue is fixed on both my Gentoo and my Fedora system.
