### ISSUE TITLE
Update Flatpak Runtime to org.freedesktop.Platform//21.08

### ISSUE THREAD

**Issue by devurandom** [flathub/org.zulip.Zulip#39]
I would like to request updating the Flatpak Runtime to org.freedesktop.Platform//21.08, so I can get rid of the old 20.08 version that only very few Flatpaks still require.

**Comment by ghisvail** [comment]
We have triggered a rebuild of the app from the last [commit](https://github.com/flathub/org.zulip.Zulip/commit/65493016a3980045d007c20f9432ab4aeb63ea9e), which includes the runtime version bump. It should be released within the day.
