### ISSUE TITLE
How to enable wayland support?

### ISSUE THREAD

**Issue by LeanderK** [flathub/org.zulip.Zulip#69]
Zulip is very blurry for me and I want to enable wayland support. I know it's experimental but I seldom have issues with vscode (which I didn't install as a flatpack application).

Is there some way to turn it one and try it out?

I've found this issue but I am not sure how to pass the arguments: https://github.com/zulip/zulip-desktop/issues/1332 (`--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`)

**Comment by andersk** [comment]
Exactly how you’d expect: `flatpak run org.zulip.Zulip --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`

Alternatively, for Electron ≥ 28 (Zulip Desktop ≥ 5.10.4), you can set the [`ELECTRON_OZONE_PLATFORM_HINT` environment variable](https://github.com/electron/electron/blob/main/docs/api/environment-variables.md#electron_ozone_platform_hint-linux) to `auto` or `wayland`.

**Comment by LeanderK** [comment]
I am on zulip `5.11` and needed to add `XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons` and `ELECTRON_OZONE_PLATFORM_HINT=auto` in Flatseal. The icon in the task bar is still buggy but now the rest works and is crisp.
